zero length elements in lifetime calculation
atcollab/at pull request #577
Opened 2023-03-09 09:32 UTC by swhite2401

This PR is a bugfix in response to issue #575. The following corrective action are impleted:
-if zero-length elements are provided, they are automatically remove with a warning
-if the user provides the momentum aperture the zero-lenght elements are also remove from the momentum aperture such that refpts and momap always remain consistent
-the momentum aperture and refpts used for the lifetime calculation (with elements removed) are returned by the function

2023-03-09 13:29 UTC, oscarxblanco commented
@swhite2401 the mask you implemented is working.
The warning output, however, seems to be shredded 
```bash
touschek.py:153: AtWarning: zero-length elements removed from lifetime calculation
  warnings.warn(AtWarning('zero-length elements removed '
```

2023-03-09 13:37 UTC, swhite2401 commented
Yes I could never find a way out of this problem: for multi-line string (required by PEP8) the message is first printed out and then the line at which it is issued is shown, this for multi-line messages results in printing only the first line....

If you have a solution for this I'dd be very happy to hear it! Or maybe @lfarv ?

2023-03-09 14:51 UTC, oscarxblanco requested changes
I did a test with a momentum aperture calculated at indexes of elements with zero-length.
The mismatch between indexes and momap is not longer present.

The warning message seems to be descriptive enough, but, the standard output is shredded.
I have put below a suggestion on how to correct this issue.

2023-03-13 11:50 UTC, swhite2401 commented
@oscarxblanco I have implemented the requested changes

2023-03-13 14:56 UTC, oscarxblanco approved these changes

2023-03-13 15:56 UTC, merged

2023-03-13 16:53 UTC, oscarxblanco commented
@swhite2401 
Unfortunately this modification introduced a bug when calculating the lifetime without the momap input.
```
 ... acceptance/touschek.py", line 156, in get_lifetime
    refpts = refpts[mask]
TypeError: range indices must be integers or slices, not list
```

It could be fixed by making refpts a numpy array.
```
refpts = numpy.array(refpts[mask])
```

2023-03-13 17:13 UTC, oscarxblanco reviewed
One modification required to be compatible with no momap input file option.

2023-03-13 17:13 UTC, oscarxblanco commented on pyat/at/acceptance/touschek.py
>          refpts = range(len(ring))
```python
refpts = numpy.array(range(len(ring)))
```