Matching fixes
atcollab/at pull request #615
Opened 2023-06-06 16:44 UTC by swhite2401

Couple bugs were found in the matching module:

- The ordering of positional and keyword argument in Variable class was wrong and is was not possible to pass args to the set/get functions. args is not set as a keyword with type tuple
- use_integer option in LinoptConstraint was not working do to a problem with the logic

These are now fixed.

In addition an improved handling of phase advance avoiding modulos in users script not matching integer part of the tune is added. Finally for 2D and 4D linopt calculations, the AtError 'Unstable ring' is caught and sent back as warning, in which case NaN are returned

2023-06-06 20:16 UTC, lfarv requested changes

2023-06-06 20:16 UTC, lfarv commented on pyat/at/physics/linear.py
> +
Isn't this debug output ?

2023-06-06 20:17 UTC, lfarv commented on pyat/at/physics/linear.py
> +
Otherwise it's ok for me!

2023-06-06 20:22 UTC, lfarv commented on pyat/at/matching/matching.py
> +                 args: tuple = (), **kwargs):
Detail: to avoid confusion with the usual `*args` (variable argument list), would this  be better named `fun_args`, or something better?

2023-06-07 06:21 UTC, swhite2401 commented
@simoneliuzzo , is this ok for you? You will have to remove the modulo on the desired phase in your matching jobs as discussed yesterday.

2023-06-07 06:35 UTC, lfarv approved these changes
For Nans instead of errors, the rule is not clear. For safety. penalty evaluation functions should be prepared for both possibilities.

2023-06-07 07:26 UTC, swhite2401 commented
> For Nans instead of errors, the rule is not clear. For safety. penalty evaluation functions should be prepared for both possibilities.

True, to be kept in mind for the new matching module

2023-06-13 07:20 UTC, swhite2401 commented
I just checked with @simoneliuzzo this is ok so I merge it

2023-06-13 07:20 UTC, swhite2401 commented
@lfarv could you re-approve? I just made some pep8 fixes

2023-06-13 18:08 UTC, lfarv approved these changes
Still ok !

2023-06-14 06:51 UTC, merged