Added EnergyLossRadPass
atcollab/at pull request #632
Opened 2023-07-24 14:39 UTC by lfarv

This is a tentative answer to #629. A new passmethod simulates an arbitrary energy loss. Damping times are affected accordingly. Equilibrium emittances also, but since there is no diffusion term associated, the computed emittances assume that th losses occur in a non-dispersive location.

The "energy loss" element is defined by the energy loss in eV, and the energy of the circulating beam (as the other radiating elements).

2023-07-24 14:46 UTC, lfarv commented
Hello @lnadolski,
This is the 1st step: no new element class, so for the moment, the element must be defined as:
```python
eloss = at.Marker('name', PassMethod='EnergyLossRadPass', EnergyLoss=40000.0, Energy=6.0e9)
```
Or, in Matlab:
```Matlab
eloss=atmarker('name','PassMethod','EnergyLossRadPass','EnergyLoss',40000.0,'Energy',6e9);
```

It is not yet handled by `enable_6d`/`disable_6d`, so you should append it to a ring where 6d is already enabled.
However, I would appreciate some tests to validate the concept.

2023-07-24 15:30 UTC, lnadolski commented on atintegrators/EnergyLossRadPass.c
> +        mxSetCell(plhs[0],1,mxCreateString("EnergyLoss"));
mxSetCell(plhs[0],1,mxCreateString("Energy"));

2023-07-24 16:26 UTC, lfarv commented on atintegrators/EnergyLossRadPass.c
> +        mxSetCell(plhs[0],1,mxCreateString("EnergyLoss"));
Corrected!

2023-07-24 16:28 UTC, lfarv commented
I did some tests in python, not yet in Matlab

2023-07-24 23:33 UTC, lnadolski commented
Dear @lfarv 

I will come back to you tomorrow to review the code.
It seems to works well for matlab

<img width="534" alt="image" src="https://github.com/atcollab/at/assets/3135838/62b61349-1eba-48d7-a094-4943277cf881">

The new damping times seem fine.
U0 for the bare lattice is 457 keV with damping times of 7.8/14.2/12.2 ms Jx is 1.83
U0 with extra loss is 946 keV with damping times of 49/69/43 ms Jx becomes 1.40 as expected from simple analytical computation

atx does not fully work, waiting to get atdisable6d fixed  ;-)
U0 is correct using the tracking option.

U0 = atgetU0(myringRadOn, 'method', 'tracking');

Regarding the 6D closed orbit, the fixed point for the energy is -201 keV for the nominal lattice and -657 keV.
Does it make sense to you not to get something closer to 0 keV ?

Regards,

Laurent.

2023-07-25 10:39 UTC, lnadolski commented
Fitting the envelop, I have got : a longitudinal damping time of 

- 10830 turns (theory at zero amplitude : 9858)
- 3746 turns (theory at zero amplitude : 3634)

![image](https://github.com/atcollab/at/assets/3135838/6e960453-ffba-4879-9237-3fa5f1e5d75d)

2023-07-25 11:37 UTC, lfarv commented
@lnadolski : all this looks nice! I'm going on with the dedicated element class.

2023-07-25 13:30 UTC, lnadolski commented
Dear @lfarv 

For me, the Matlab version is fine and fulfills the goal.
To be improved: The code does not complain is the energy is missing

2023-07-25 16:57 UTC, lfarv commented
@lnadolski : the Energy field is now handled by the enable/disable_6d method, as it is for magnetic elements (dipoles)
- the element constructor sets the passmethod to 'IdentityPass': by default, it's disabled.
- the Energy field is added or removed when enabling/disabling longitudinal motion, exactly as for dipoles

Saving/loading works,
The total energy loss is correctly computed for both 'integral' and 'tracking' methods

For me, it's ready.

2023-07-26 06:11 UTC, lnadolski requested changes
ringpara need some update

2023-07-26 14:12 UTC, lnadolski approved these changes
This works well for me!

2023-07-31 12:52 UTC, lfarv commented
@lnadolski: a new approval is needed after solving conflicts with the master branch…

2023-07-31 17:32 UTC, merged